[package]
name = "request_cache"
version = "0.2.0"
edition = "2021"
readme = "README.md"
exclude = [
    "target/*",
    "examples/*/target/*",
    "*.db",
    "test_*",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-sqlite = "0.3.1"
reqwest = { version = "0.12.4", features = ["blocking"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
url = "2.5"
